import logging

from audit_logs.models import AuditAction
from audit_logs.services import AuditLogService
from dashboard.services.dashboard_service import DashboardService
from django.contrib.auth import get_user_model
from django.db import transaction
from incidents.models import Incident, IncidentSeverity
from incidents.utils.cache import clear_dashboard_cache

logger = logging.getLogger(__name__)

User = get_user_model()


class AutoIncidentService:
    """
    Creates incidents automatically from security detections.

    This service is separate from IncidentService because
    automated detections do not use DRF serializers.
    """

    SYSTEM_USERNAME = "soc-detection-engine"

    @classmethod
    def _get_system_user(cls):
        """
        Get or create the internal detection-engine user.
        """

        lookup_field = User.USERNAME_FIELD

        user, created = User.objects.get_or_create(
            **{
                lookup_field: cls.SYSTEM_USERNAME,
            }
        )

        if created:
            user.is_active = True
            user.set_unusable_password()
            user.save()

        return user

    @staticmethod
    def _normalize_severity(severity):
        """
        Ensure only valid incident severity values are used.
        """

        if severity in IncidentSeverity.values:
            return severity

        return IncidentSeverity.MEDIUM

    @staticmethod
    def _refresh_dashboard():
        """
        Clear dashboard cache and broadcast fresh data.
        """

        clear_dashboard_cache()

        try:
            DashboardService.broadcast_dashboard()
        except Exception:
            logger.exception(
                "Dashboard broadcast failed after "
                "automatic incident creation."
            )

    @classmethod
    def create_incident(
        cls,
        *,
        title,
        description,
        severity=IncidentSeverity.MEDIUM,
    ):
        """
        Create an incident generated by the detection engine.
        """

        if not title or not str(title).strip():
            raise ValueError(
                "Auto incident title is required."
            )

        system_user = cls._get_system_user()

        severity = cls._normalize_severity(
            severity
        )

        with transaction.atomic():
            incident = Incident.objects.create(
                title=str(title).strip(),
                description=str(description or "").strip(),
                severity=severity,
                created_by=system_user,
            )

            AuditLogService.create_log(
                user=system_user,
                incident=incident,
                action=AuditAction.CREATED,
                description=(
                    f"Detection engine automatically created "
                    f"incident {incident.incident_id}."
                ),
            )

            transaction.on_commit(
                cls._refresh_dashboard
            )

        return incident