# Generated by Django 6.0.5 on 2026-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
