# Generated by Django 6.0.5 on 2026-07-24 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=500)),
                ('ioc_type', models.CharField(choices=[('IP_ADDRESS', 'IP Address'), ('DOMAIN', 'Domain'), ('URL', 'URL'), ('FILE_HASH', 'File Hash')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicator of Compromise',
                'verbose_name_plural': 'Indicators of Compromise',
                'db_table': 'indicators_of_compromise',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('ioc_type', 'value'), name='unique_ioc_type_value')],
            },
        ),
    ]
